name: CI
on:
  # Triggers the workflow on push for all branches
  push:
  # Triggers the workflow on pull request on the develop and main branch
  pull_request:
    branches:
      - main
      - develop
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: test_environment
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install all dependencies
        run: npm install
      - name: Check linting errors
        run: npm run lint
      - name: Run tests and generate coverage reports
        run: npm run coverage
      - name: Sending coveralls report
        uses: coverallsapp/github-action@master
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to codeclimate
        uses: paambaati/codeclimate-action@v2.5.7
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_REPORTER_ID}}
